
export type Language = 'es' | 'en';

// Define the shape of the translations to ensure consistency between languages and fix type errors in App.tsx
export const translations = {
  es: {
    sidebar: { overview: 'Vista General', patients: 'Pacientes', doctors: 'Cuerpo Médico', settings: 'Configuración', logout: 'Cerrar Sesión', tipTitle: 'Consejo Clínico', tipContent: 'El Pulso Artificial (AP) se activa a > 4000 RPM para reducir el riesgo de trombosis.' },
    header: { searchPlaceholder: 'Buscar...', drName: 'Dra. Juana Díaz' },
    dashboard: { title: 'Panel Clínico', subtitle: 'Estado en tiempo real de la cohorte.', totalPatients: 'Total Pacientes', stable: 'Estables', critical: 'Crítico/Atención', monitoring: 'Monitoreo', activeAlerts: 'Alertas Activas', newAlerts: 'Nuevas', allSystemsNormal: 'Sistemas normales', distributionTitle: 'Distribución por Estado', flow: 'Flujo', power: 'Potencia', inr: 'INR', statusLabels: { stable: 'Estable', caution: 'Precaución', critical: 'Crítico' } },
    patientList: { title: 'Registro de Pacientes', subtitle: 'Gestione el seguimiento LVAD.', newPatient: 'Nuevo Paciente', totalEntries: 'entradas', filter: 'Filtrar', table: { name: 'Paciente', surgery: 'Cirugía', flow: 'Flujo', inr: 'INR', status: 'Estado' } },
    patientDetails: { back: 'Volver', addRecord: 'Agregar Registro', profile: { id: 'ID', dob: 'Nacimiento', surgery: 'Cirugía', status: 'ESTADO' }, stats: { speed: 'Velocidad', flow: 'Flujo', power: 'Potencia', pi: 'PI' }, tabs: { trends: 'Tendencias', history: 'Historial' }, charts: { performanceTitle: 'Rendimiento HeartMate 3', anticoagulationTitle: 'Anticoagulación y Pulsatilidad', vitalsTitle: 'Signos Vitales (TAM y FC)', flowLegend: 'Flujo (L/min)', powerLegend: 'Potencia (W)', inrLegend: 'INR', piLegend: 'PI', meanBPLegend: 'TAM (mmHg)', hrLegend: 'FC (lpm)' }, table: { timestamp: 'Fecha/Hora', speed: 'RPM', flow: 'L/min', power: 'W', pi: 'PI', inr: 'INR', ta: 'TA', meanBP: 'TAM' } },
    addRecord: { title: 'Nueva Entrada', subtitle: 'Datos para', lvadStats: 'Parámetros HM3', vitals: 'Signos Vitales', speed: 'Velocidad (RPM)', flow: 'Flujo (L/min)', power: 'Potencia (W)', pi: 'PI', inr: 'INR', hr: 'FC', systolic: 'Sistólica', diastolic: 'Diastólica', meanBP: 'TAM', cancel: 'Cancelar', save: 'Guardar' },
    doctorManagement: { title: 'Cuerpo Médico', subtitle: 'Gestión de especialistas y perfiles.', newDoctor: 'Nuevo Doctor', searchPlaceholder: 'Buscar especialista...', table: { name: 'Nombre', role: 'Cargo', license: 'Colegiado', email: 'Email', actions: 'Acciones' }, currentUser: 'Usuario Actual', switchProfile: 'Cambiar a este perfil' },
    settings: { title: 'Configuración', subtitle: 'Preferencias de la plataforma.', language: 'Idioma', professionalProfile: 'Perfil', specialistManagement: 'Especialistas', clinicalCenter: 'Centro Clínico', alarmSettings: 'Alarmas', notifications: 'Notificaciones', security: 'Seguridad', currentProfile: 'Perfil Actual', fullName: 'Nombre', license: 'Colegiado', email: 'Email', changePhoto: 'Cambiar Foto', saveChanges: 'Guardar', saved: 'Guardado', registeredSpecialists: 'Registrados', add: 'Añadir', useProfile: 'Usar', centerName: 'Centro', address: 'Dirección', phone: 'Teléfono', emergency: 'Emergencia', beds: 'Camas', alarmThresholdsTitle: 'Umbrales de Alerta', alarmThresholdsSubtitle: 'Configure los disparadores automáticos.', flowMin: 'Flujo Mín.', powerMax: 'Potencia Máx.', inrMin: 'INR Mín.', inrMax: 'INR Máx.', speedMin: 'RPM Mín.', speedMax: 'RPM Máx.', piMin: 'PI Mín.' }
  },
  en: {
    sidebar: { overview: 'Overview', patients: 'Patients', doctors: 'Medical Staff', settings: 'Settings', logout: 'Logout', tipTitle: 'Clinical Tip', tipContent: 'Artificial Pulse (AP) activates at > 4000 RPM to reduce thrombosis risk.' },
    header: { searchPlaceholder: 'Search...', drName: 'Dr. Juana Díaz' },
    dashboard: { title: 'Clinical Dashboard', subtitle: 'Real-time cohort status.', totalPatients: 'Total Patients', stable: 'Stable', critical: 'Critical/Caution', monitoring: 'Monitoring', activeAlerts: 'Active Alerts', newAlerts: 'New', allSystemsNormal: 'All systems normal', distributionTitle: 'Status Distribution', flow: 'Flow', power: 'Power', inr: 'INR', statusLabels: { stable: 'Stable', caution: 'Caution', critical: 'Critical' } },
    patientList: { title: 'Patient Registry', subtitle: 'Manage LVAD follow-up.', newPatient: 'New Patient', totalEntries: 'entries', filter: 'Filter', table: { name: 'Patient', surgery: 'Surgery', flow: 'Flow', inr: 'INR', status: 'Status' } },
    patientDetails: { back: 'Back', addRecord: 'Add Record', profile: { id: 'ID', dob: 'DOB', surgery: 'Surgery', status: 'STATUS' }, stats: { speed: 'Speed', flow: 'Flow', power: 'Power', pi: 'PI' }, tabs: { trends: 'Trends', history: 'History' }, charts: { performanceTitle: 'HeartMate 3 Performance', anticoagulationTitle: 'Anticoagulation & Pulsatility', vitalsTitle: 'Vital Signs (MAP & HR)', flowLegend: 'Flow (L/min)', powerLegend: 'Power (W)', inrLegend: 'INR', piLegend: 'PI', meanBPLegend: 'MAP (mmHg)', hrLegend: 'HR (bpm)' }, table: { timestamp: 'Date/Time', speed: 'RPM', flow: 'L/min', power: 'W', pi: 'PI', inr: 'INR', ta: 'BP', meanBP: 'MAP' } },
    addRecord: { title: 'New Entry', subtitle: 'Data for', lvadStats: 'HM3 Parameters', vitals: 'Vital Signs', speed: 'Speed (RPM)', flow: 'Flow (L/min)', power: 'Power (W)', pi: 'PI', inr: 'INR', hr: 'HR', systolic: 'Systolic', diastolic: 'Diastolic', meanBP: 'MAP', cancel: 'Cancel', save: 'Save' },
    doctorManagement: { title: 'Medical Staff', subtitle: 'Specialist and profile management.', newDoctor: 'New Doctor', searchPlaceholder: 'Search specialist...', table: { name: 'Name', role: 'Role', license: 'License', email: 'Email', actions: 'Actions' }, currentUser: 'Current User', switchProfile: 'Switch to this profile' },
    settings: { title: 'Settings', subtitle: 'Platform preferences.', language: 'Language', professionalProfile: 'Profile', specialistManagement: 'Specialists', clinicalCenter: 'Clinical Center', alarmSettings: 'Alarms', notifications: 'Notifications', security: 'Security', currentProfile: 'Current Profile', fullName: 'Name', license: 'License', email: 'Email', changePhoto: 'Change Photo', saveChanges: 'Save Changes', saved: 'Saved', registeredSpecialists: 'Registered', add: 'Add', useProfile: 'Use', centerName: 'Center', address: 'Address', phone: 'Phone', emergency: 'Emergency', beds: 'Beds', alarmThresholdsTitle: 'Alert Thresholds', alarmThresholdsSubtitle: 'Configure automatic triggers.', flowMin: 'Min Flow', powerMax: 'Max Power', inrMin: 'Min INR', inrMax: 'Max INR', speedMin: 'Min RPM', speedMax: 'Max RPM', piMin: 'Min PI' }
  }
};
